github: [vytravyctoria]
open_collective: vytravyctoria
ko_fi: vytravyctoria
liberapay: vytravyctoria
issuehunt: vytravyctoria
polar: vytravyctoria
buy_me_a_coffee: vytravyctoria
thanks_dev: vytravyctoria
custom: ['https://paypal.me/vytravyctoria', 'https://solscan.io/account/36f9QZafJWEtTVHywuKqBQDjNmWCJoHaTCep3Mmwegbc']
